[build]
  publish = "static"
  command = "mix local.hex --force && mix build"

[build.environment]
  ELIXIR_VERSION = "1.17.3"
  ERLANG_VERSION = "26.0.2"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"
    Cross-Origin-Resource-Policy = "cross-origin"
